### ISSUE TITLE
API not working?

### ISSUE THREAD

**Issue by quranwbw** [stefanzweifel/screeenly#317]
I'm trying to use the API but it's not working. I already have the key and I'm directly using the API in the browser. The error that I'm getting is:

`{"title":"An error accoured","message":"An internal error accoured."} `

The URL that I'm using is:

`http://screeenly.com/api/v1/fullsize?key=API_KEY&url=google.com`

Any idea what's wrong?

**Comment by stefanzweifel** [comment]
Hi there,

The problem is probably that `google.com` is not a valid URL. A URL should look like this: `https://google.com`

You can find the documentation off the API [here](https://github.com/stefanzweifel/screeenly/wiki/Use-the-API) and a PHP Curl example [here](https://gist.github.com/stefanzweifel/968e68785277013ac214).
