### ISSUE TITLE
Lots of bad requests

### ISSUE THREAD

**Issue by borislavgit** [stefanzweifel/screeenly#50]
Hey stefan, 

love what you've done with your API, it's really useful as a service for quickly getting what you want. But I find that I get a lot of bad requests call on multiple urls and I can't figure out why. I'm going to post some urls:

- http://pathogenomics.sfu.ca/islandviewer
- http://mdl.shsmu.edu.cn/ASD/
- http://homingendonuclease.net
- http://bidd.nus.edu.sg/group/ttd/ttd.asp (this one has a redirect, but the others don't)
- http://bioinformatics.mdanderson.org/SurvNet/

Do you have some idea why it can't capture the screenshots?

**Comment by stefanzweifel** [comment]
Hey

Thanks for your message. Might this be related to #44 ? Are these URLs always failing?

*I was quite busy the last weeks and Screeenly didn't get the attention it should have. I will look into your errors in the upcoming days.*

**Comment by borislavgit** [comment]
I can't tell you for sure, I tried to capture http://mdl.shsmu.edu.cn/ASD/ at least 10 times but it failed at each try. I'll investigate the CloudFlare on our side.

**Comment by stefanzweifel** [comment]
Hey

I will close this issue, because it basically a duplicate to #44. I've written a [reply](https://github.com/stefanzweifel/screeenly/issues/44#issuecomment-220786124) in the other issue-thread with some more information about how this error accours and how it could be fixed.

If you wan't to be notified about changes I recommend subscribing to the other thread.
